import { Task } from "./task-types";

export const initialTasks: Task[] = [
  // Assigned tasks
  {
    id: "ta-1",
    title: "Revisar planos estructurales",
    status: "assigned",
    order: 0,
    priority: "Alta",
    assignedTo: "Carlos Mendoza",
    dueDate: "15 Feb 2026",
  },
  {
    id: "ta-2",
    title: "Cotizar materiales",
    status: "assigned",
    order: 1,
    priority: "Media",
    assignedTo: "Ana García",
    dueDate: "12 Feb 2026",
  },
  {
    id: "ta-3",
    title: "Supervisar cimentación",
    status: "assigned",
    order: 2,
    priority: "Alta",
    assignedTo: "Luis Torres",
    dueDate: "18 Feb 2026",
  },

  // Received tasks
  {
    id: "tr-1",
    title: "Actualizar presupuesto",
    status: "received",
    order: 0,
    priority: "Alta",
    from: "Director de Proyecto",
    receivedDate: "2026-02-10",
  },
  {
    id: "tr-2",
    title: "Entregar informe semanal",
    status: "received",
    order: 1,
    priority: "Media",
    from: "Gerencia",
    receivedDate: "2026-02-09",
  },
  {
    id: "tr-3",
    title: "Coordinar con proveedores",
    status: "received",
    order: 2,
    priority: "Baja",
    from: "Compras",
    receivedDate: "2026-02-08",
  },
  {
    id: "tr-4",
    title: "Revisar contratos",
    status: "received",
    order: 3,
    priority: "Alta",
    from: "Legal",
    receivedDate: "2026-02-06",
  },
  {
    id: "tr-5",
    title: "Preparar presentación",
    status: "received",
    order: 4,
    priority: "Media",
    from: "Director de Proyecto",
    receivedDate: "2026-02-04",
  },

  // Completed tasks
  {
    id: "tf-1",
    title: "Diseño de fachada principal",
    status: "completed",
    order: 0,
    completedBy: "María López",
    completedDate: "2026-02-08",
  },
  {
    id: "tf-2",
    title: "Aprobación de permisos",
    status: "completed",
    order: 1,
    completedBy: "Juan Pérez",
    completedDate: "2026-02-05",
  },
  {
    id: "tf-3",
    title: "Instalación eléctrica fase 1",
    status: "completed",
    order: 2,
    completedBy: "Roberto Sánchez",
    completedDate: "2026-02-03",
  },
  {
    id: "tf-4",
    title: "Revisión de planos",
    status: "completed",
    order: 3,
    completedBy: "María López",
    completedDate: "2026-01-28",
  },
  {
    id: "tf-5",
    title: "Entrega de documentos",
    status: "completed",
    order: 4,
    completedBy: "Ana García",
    completedDate: "2026-01-25",
  },
];
